services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: pharmavig_postgres
    environment:
      POSTGRES_DB: pharmavigilance
      POSTGRES_USER: pv_user
      POSTGRES_PASSWORD: pv_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/etl/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pv_user -d pharmavigilance"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: